### ISSUE TITLE
EKS issues noted during testing.

### ISSUE THREAD

**Issue by adamlong-foxsports** [codedropau/efs-provisioner#2]
Hello! 

I had a good look at this provisioner today and stumbled on a number of issues which are I think are worth sharing with maintainers.

- There should be a Helm chart or Kustomization for the required resources. [opinion]
- There are some ENV vars which are incorrectly named in the deployment example AWS_SECURITY_GROUP and AWS_SUBNETS should be EFS_PROVISIONER_SECURITYGROUP and EFS_PROVISIONER_SUBNETS
- API_VERSION env var is under documented in the controller
- RBAC resources docs are completely missing yet required in most clusters where default service accounts don't have super powers. I have added roles and bindings for a new serviceaccount below which allows the controller to run without error. 
- This looks to be targeting older EKS/K8s APIs which are incompatible with v1.18^ an example for this; Deployment requires selector labels (but I find a few other API issues)
- There is a typo in the image name `coderdropau/efs-provisioner:latest` should be `codedropau/efs-provisioner:latest`
- Even with all the above and the controller running successfully without error there is no logging watching and reconcilation PVCs in any namespace or of any failures in IAM permissions or EFS provisioning errors, it is just kind of doing nothing.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: efs-provisioner
  name: efs-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: efs-provisioner
  name: efs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: efs-provisioner
subjects:
- kind: ServiceAccount
  name: efs-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: efs-provisioner
  name: efs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: efs-provisioner
subjects:
- kind: ServiceAccount
  name: efs-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: efs-provisioner
  name: efs-provisioner
rules:
- apiGroups:
  - v1
  resources:
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - "storageclasses"
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - v1
  - events.k8s.io/v1
  resources:
  - "events"
  verbs:
  - list
  - watch
  - create
  - update
  - get
```
